sonar.projectKey=student-management-ofppt
sonar.projectName=Student Management OFPPT
sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src/tests,backend/src
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
